title: Birding Site Impressions
description: Birding Site Impressions

# Build settings
markdown: kramdown
theme: minima

collections:
  sites:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "sites"
    values:
      layout: "location"

exclude:
  - bin
  - venv