title: Washington Birding Site Impressions
description: Washington Birding Site Impressions

# Build settings
markdown: kramdown
theme: minima

collections:
  sites:
    output: true

exclude:
  - bin
  - venv