title: Washington Birding Site Impressions
description: Washington Birding Site Impressions
baseurl: /wabirding

# Build settings
markdown: kramdown
theme: minima

collections:
  sites:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "sites"
    values:
      layout: "page"

exclude:
  - bin
  - venv